# Generated by Django 3.0 on 2020-07-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usreg',
            name='imgup',
            field=models.ImageField(null=True, upload_to='document/'),
        ),
    ]
